### ISSUE TITLE
Settings page has "switch value" visible 

### ISSUE THREAD

**Issue by D00264512** [TanishAfre/FocusMind#50] opened 2024-02-26 14:43 UTC
In the settings page under blackout mode the option "Disable keyboard" has the following visible "Switch value"
Note :- The on and off state should be only visible for the user by the means of slider button and not the text 

STR :-
1) Launch the application
2) Navigate to the settings page
3) Scroll down to the "blackout mode" section
4) notice the text under the "disable keyboard" slider button

Issue occurrence probability - 5/5

**Comment by Ferreter** [comment] 2024-02-29 20:58
Duplicate of  ' Settings page has "true" "false" text visible #51'

**Closed as completed by Ferreter** 2024-02-29 20:58 UTC
